language: 
solution: Facebook.sln

matrix:
  include:
    - os: osx
      dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1;TRAVIS_NODE_VERSION=6.10.2;CLI_VERSION=1.1.1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1;TRAVIS_NODE_VERSION=6.10.2;CLI_VERSION=1.1.1

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION

cache:
  directories:
    - node_modules
    - $HOME/.pub-cache
before_script:
  - chmod a+x ./build.sh
  
script:
  - ./build.sh --quiet verify
