version: '2.1'

services:
  facebook:
    image: facebook
    build:
      context: ./src/Facebook.WebApplication
      dockerfile: Dockerfile

  facebook.identityprovider:
    image: facebook.identityprovider
    build:
      context: ./src/Facebook.IdentityProvider
      dockerfile: Dockerfile
