version: '2.1'

services:
  facebook:
    image: facebook
    build:
      context: .
      dockerfile: Dockerfile

  facebook.identityprovider:
    image: facebook.identityprovider
    build:
      context: ./../Facebook.IdentityProvider
      dockerfile: Dockerfile
